# Mean, variance and Standard deviation calculator

## Call libraries

first step is call the libraries that are goinng to use to create this project.

In [1]:
import numpy as np
import pandas as pd

## List

Now, a nine-values list is needed.

In [2]:
list = []

for i in range(9):
    i = float(input("Insert a float number: "))
    list.append(i)
print(list)


[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]


## Create a matrix 3x3.

Now, the _list_ created before will be reshaped to create a 3x3 matrix

In [3]:
matrix = np.reshape(list, (3,3))
print(matrix)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


## Create the function _calculate_.
This project intructions says that is needed to create a fuction named _calculate_ that claculates the mean, variance, standard deviation, max, min and the sum of the matrix created above. The creation of the function is shown ahead.

In [4]:
def calculate(M):
    mean, meanC, meanR = np.mean(matrix), np.mean(matrix, axis = 0).tolist(), np.mean(matrix, axis = 1).tolist()
    var, varC, varR = np.var(matrix), np.var(matrix, axis = 0).tolist(), np.var(matrix, axis = 1).tolist()
    std, stdC, stdR = np.std(matrix), np.std(matrix, axis = 0).tolist(), np.std(matrix, axis = 1).tolist()
    max, maxC, maxR = np.max(matrix), np.max(matrix, axis = 0).tolist(), np.max(matrix, axis = 1).tolist()
    min, minC, minR = np.min(matrix), np.min(matrix, axis = 0).tolist(), np.min(matrix, axis = 1).tolist()
    sum, sumC, sumR = np.sum(matrix), np.sum(matrix, axis = 0).tolist(), np.sum(matrix, axis = 1).tolist()
    
    mean_dic = [meanC, meanR, mean]
    var_dic = [varC, varR, var]
    std_dic = [stdC, stdR, std]
    max_dic = [maxC, maxR, max]
    min_dic = [minC, minR, min]
    sum_dic = [sumC, sumR, sum]
    



    
          

    dictionary = {'mean': mean_dic,
                  'variance': var_dic,
                   'standard deviation': std_dic,
                    'max': max_dic,
                     'min': min_dic,
                      'sum': sum_dic
                        }
    

    return dictionary

solve = calculate(matrix)

print(solve)





{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0], 'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667], 'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611], 'max': [[6.0, 7.0, 8.0], [2.0, 5.0, 8.0], 8.0], 'min': [[0.0, 1.0, 2.0], [0.0, 3.0, 6.0], 0.0], 'sum': [[9.0, 12.0, 15.0], [3.0, 12.0, 21.0], 36.0]}


## Conclutions.

This is how a statistics calculator is made. Note that the result obtained is a dictionary and the values tested are same as example values, so it is valid to conclude that the function named _calculate_ works good. 